main: de.thojo0.moreheadsounds.App
name: MoreHeadSounds
version: 1.2
authors: [thojo0, PYZ]
description: Allows the use of player heads for minecraft sounds
api-version: 1.20
commands:
  moreheadsounds:
    description: The main command for MoreHeadSounds
    usage: /<command>
permissions:
  moreheadsounds.reload:
    description: Allows reloading the configuration
  moreheadsounds.clearItem:
    description: Allows clearing the sound of the currently holding player head
    default: true
  moreheadsounds.getHash:
    description: Allows reading the texture hash of the currently holding player head